source 'https://github.com/CocoaPods/Specs.git'
platform :ios,			'8.0'
#inhibit_all_warnings!

target:'MLCKitDemo'

pod 'Masonry', '1.1.0'
pod 'YYCache', '1.0.4'
pod 'YYModel', '1.0.4'
pod 'MLCKit', :path => '../', :modular_headers => true
#pod 'MLCKit', :git => 'https://github.com/mlcldh/MLCKit.git', :commit => '3fe5931'

#use_modular_headers!
