source 'https://github.com/CocoaPods/Specs.git'
platform :ios,			'8.0'
#inhibit_all_warnings!

target:'MLCKitDemo'

pod 'Masonry', '1.1.0'
pod 'YYCache', '1.0.4'
pod 'YYModel', '1.0.4'
pod 'MLCKit', :path => '../../MLCKit'
#pod 'MLCKit', :git => 'https://github.com/mlcldh/MLCKit.git', :commit => 'e6b238b'
